//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAppointmnet
    {
        public int AppointmentId { get; set; }
        public string Patientname { get; set; }
        public string Specialization { get; set; }
        public string ConsultingDoctor { get; set; }
        public string AppointmentDate { get; set; }
        public string AppointmentTime { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> DoctorId { get; set; }
    
        public virtual managedoctor managedoctor { get; set; }
        public virtual patient patient { get; set; }
    }
}
