//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dischargesum
    {
        public int DischargeId { get; set; }
        public string Patientname { get; set; }
        public string AdmissionDate { get; set; }
        public string DischargeDate { get; set; }
        public string Doctorname { get; set; }
        public string DischargeDiagnosis { get; set; }
        public string Complications { get; set; }
        public Nullable<int> InPatientId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string ConditionOnDischarge { get; set; }
    
        public virtual managedoctor managedoctor { get; set; }
        public virtual InPatient InPatient { get; set; }
    }
}
