//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class managedoctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public managedoctor()
        {
            this.BookAppointmnets = new HashSet<BookAppointmnet>();
            this.Prescriptions = new HashSet<Prescription>();
            this.Dischargesums = new HashSet<Dischargesum>();
        }
    
        public int DoctorId { get; set; }
        public string DoctorName { get; set; }
        public Nullable<int> PhoneNo { get; set; }
        public string Specialization { get; set; }
        public int Experience { get; set; }
        public string Qualification { get; set; }
        public int ConsultationFee { get; set; }
        public string PhoneNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAppointmnet> BookAppointmnets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dischargesum> Dischargesums { get; set; }
    }
}
