//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class managetip
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string WellnessTips { get; set; }
        public string BlogLink { get; set; }
        public string Youtubelink { get; set; }
        public string Symptoms { get; set; }
        public string Prevention { get; set; }
    }
}
