//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int PrescriptionId { get; set; }
        public string PrescriptionDate { get; set; }
        public string Drugnamedosage { get; set; }
        public string DrugDuration { get; set; }
        public string patientname { get; set; }
        public string doctorname { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> Column_Age { get; set; }
    
        public virtual managedoctor managedoctor { get; set; }
        public virtual patient patient { get; set; }
    }
}
